// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdutg4pCgJDEDw-SrPraHvPJcpttQm6RQ',
    appId: '1:131886292417:web:a05f630dd24400975e6340',
    messagingSenderId: '131886292417',
    projectId: 'edu-hub-b9813',
    authDomain: 'edu-hub-b9813.firebaseapp.com',
    storageBucket: 'edu-hub-b9813.appspot.com',
    measurementId: 'G-MNHD0JETN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm_igSsaTQy6l_XSDMll2PprNZkeqDGAg',
    appId: '1:131886292417:android:28f9fba18d5f26c75e6340',
    messagingSenderId: '131886292417',
    projectId: 'edu-hub-b9813',
    storageBucket: 'edu-hub-b9813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-xnsfTB5OF_54xU-G0rpi5HBqf0eIzZg',
    appId: '1:131886292417:ios:b1c4a14ce7e8a8145e6340',
    messagingSenderId: '131886292417',
    projectId: 'edu-hub-b9813',
    storageBucket: 'edu-hub-b9813.appspot.com',
    iosBundleId: 'com.example.mini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-xnsfTB5OF_54xU-G0rpi5HBqf0eIzZg',
    appId: '1:131886292417:ios:e8a4ea22576295dc5e6340',
    messagingSenderId: '131886292417',
    projectId: 'edu-hub-b9813',
    storageBucket: 'edu-hub-b9813.appspot.com',
    iosBundleId: 'com.example.mini.RunnerTests',
  );
}
